name: test_npm_build

on:	
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test_npm_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 'latest'

    - name: Install project dependencies
      run: npm install

    - name: Create a website page
      run: |
        npm run build
